#pragma once
#include "cv.h"
#include "highgui.h"
#include <opencv2/core/core.hpp>
#include <opencv2/highgui/highgui.hpp>
#include <opencv2/video/background_segm.hpp>

using namespace cv;

class VehicleRecognizer
{
private:
	//FileName
	string SourceFileName;
	//Current frame
	Mat frame;
	//fg mask generated by MOG method
	Mat fgMaskMOG;
	//MOG Background substractor
	//Ptr<BackgroundSubtractor> pMOG;
	BackgroundSubtractorMOG2 MOG2;
	BackgroundSubtractorMOG MOG;
	VideoCapture capture;
	//String stream for frame number
	std::stringstream ss;
	//Use MOG2 substraction method flag
	bool mbUseMOG2;
public:
	bool ProcessNextFrame();
	Mat getNextFrameMat();
	//Gets source filename.
	string getSourceVideoFileName();
	//Sets source filename.
	void setSourceVideoFileName(string SourceVideoFileName);
	/*
	Constructor
	*/
	VehicleRecognizer(string SourceVideoFileName, bool UseMOG2Substraction = false);
	/*
	Default constuctor
	*/
	VehicleRecognizer(void);
	/*
	Default destructor
	*/
	~VehicleRecognizer(void);
};

