#pragma once
#include "cv.h"
#include "highgui.h"
#include <opencv2/core/core.hpp>
#include <opencv2/highgui/highgui.hpp>
#include <opencv2/video/background_segm.hpp>

using namespace cv;

class VehicleRecognizer
{
private:
	char* SourceFileName;
	//Current frame
	Mat frame;
	//fg mask generated by MOG method
	Mat fgMaskMOG;
	//fg mask generated by MOG2 method
	Mat fgMaskMOG2;
	//MOG Background substractor
	Ptr<BackgroundSubtractor> pMOG;
	//MOG2 Background substractor
	Ptr<BackgroundSubtractor> pMOG2;
	VideoCapture capture;
	//String stream for frame number
	std::stringstream ss;
public:
	
	bool ProcessNextFrame();
	Mat getNextFrameMat();
	//Gets source filename.
	char* getSourceVideoFileName();
	//Sets source filename.
	void setSourceVideoFileName(char *SourceVideoFileName);
	/*
	Constructor
	*/
	VehicleRecognizer(char *SourceVideoFileName);
	/*
	Default constuctor
	*/
	VehicleRecognizer(void);
	/*
	Default destructor
	*/
	~VehicleRecognizer(void);
};

